CREATE TABLE log (
    `ID` BIGINT(20) AUTO_INCREMENT,
    `TITLE` VARCHAR(100) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `CREATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='日志表';