CREATE TABLE user (
    `ID` BIGINT(20) unsigned zerofill NOT NULL,
    `USERNAME` VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `LOCKED` INT DEFAULT 0 COMMENT '用户是否锁定，0：正常，1：锁定',
    `ROLEIDS` VARCHAR(100) NULL DEFAULT NULL COMMENT '用户角色ID列表，用，分隔',
    PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE role (
    `ID` BIGINT(20) unsigned zerofill NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `DESCRIPTION` VARCHAR(100) NOT NULL,
    `LOCKED` INT DEFAULT 0 COMMENT '角色是否锁定，0：正常，1：锁定',
    `RESOURCEIDS` VARCHAR(100) NULL DEFAULT NULL COMMENT '资源ID列表，用，分隔',
    PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色表';